# Generated by Django 5.1.4 on 2025-01-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_task_delete_taskmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
    ]
